### PR TITLE
Update AlphaAnimals_CE_Patch_Race_Skyeel.xml

### PR DESCRIPTION
**Pull request by Breadbox2k19**

### CODE REVIEW

**Comment by Juanfrank** [comment]
See #85

**Comment by Breadbox2k19** [comment]
Wait, doesn’t CE has electric damage that bypasses sharp and blunt armour, we should just use that.

**Comment by Juanfrank** [comment]
I think so? I'm not really sure. AA's works fine too. It incaps for like 3 hours ig

**Comment by Breadbox2k19** [comment]
CE’s electric damage doesn’t incapacitates, I’ll just stick with AA electric damage.

**Pull request merged**
