### PR TITLE
Update AlphaAnimals_CE_Patch_Race_Siegebreaker.xml

### PR DESCRIPTION
**Pull request by Breadbox2k19**
Increased bulk and weight capacity so that it could spawn with the required ammo.
Siege breaker now use siege turret as its weapon.
Increased armor because it's a tonk.

### CODE REVIEW

**Comment by Juanfrank** [comment]
I'll test this one myself since I've seen how turretbases go crazy when attaching weapons to them.

**Comment by Juanfrank** [comment]
Also I agree with the armor change since it's similar to the vanilla centipede armor which is the creature that this reverts back to when it's deactivated in the AA Mod Options.

**Comment by Breadbox2k19** [comment]
How did it go? It was working exactly as intended on my end.

**Comment by Juanfrank** [comment]
Sorry I'm actually working rn just able to do quick reads and replies.

**Review by Juanfrank — APPROVED** [review]

**Pull request merged**
