### PR TITLE
Update AlphaAnimals_CE_Patch_Race_Boulder_Mit.xml

### PR DESCRIPTION
**Pull request by Breadbox2k19**
20 and 75 rha is abit too excessive. However, despite the armor, due to the creature lacking in all-round armor coverage. The creature would prove to be frailer than expected, perhaps make a custom body with complete armor coverage and patch this creature to use it?

### CODE REVIEW

**Comment by Juanfrank** [comment]
Some request made me consider removing armor from his visible non-armored parts, such as head, eyes, etc. I'll check it and worst case scenario I'll change their coverage values to decrease the hit chance.

**Comment by Juanfrank** [comment]
Also the summitcrab is literally a mountain.

**Comment by Breadbox2k19** [comment]
> Also the summitcrab is literally a mountain.

A mountain yes, but there should be a reasonable way to kill it considering that the event basically says 'You better kill the thing before it flattens your base'.

**Comment by Juanfrank** [comment]
You can always RPG it like the standard mechanoid strategy.

**Comment by Breadbox2k19** [comment]
Bouldermitt and summitcrab blunt armor buffed up.

**Review by Juanfrank — APPROVED** [review]

**Pull request merged**
