### PR TITLE
Update AlphaAnimals_CE_Patch_Race_Mammoth_Worm.xml

### PR DESCRIPTION
**Pull request by Breadbox2k19**
30 RHA is incredibly excessive unless its combat power is greatly increased, 30rha is basically game over for early colonies. Centipedes will only spawn for mid-late game colonies, mammoth worms could spawn for early colonies.

### CODE REVIEW

**Comment by Juanfrank** [comment]
I believe AA's author already warns of the OPness of the Black Hive in early game, giving the player the option to disable it early on. Therefore I think the warning should apply even now.

Even so, I think CE actually helps against these creatures, and considering this one's movement speed it might take a while but you could take it down with cheesing, given that the other BH's creatures were killed.

**Comment by Juanfrank** [comment]
Also Centipede has 45 Blunt 20 Sharp, and taking into consideration that it was designed to fight mechanoids, and that "While generally peaceful, if provoked, it becomes a terrifying force that can rival those of mechanoid Centipedes", I think these stats are warranted.

**Comment by Breadbox2k19** [comment]
Black hives aren't supposed to be OP at all, they are easily manageable in vanilla. Being OP or need to be disabled at the start is straight-up bad balance.
30 Rha is near totally invulnerable to none rockets attacks, if you think that's fair, then it needs to be patched a have a far higher combat power.

**Comment by Juanfrank** [comment]
I'll adjust the values to make more easily accesible AP ammo be able to hit him.

**Pull request merged**
