### PR TITLE
Update AlphaAnimals_CE_Patch_Race_Black_Hive.xml

### PR DESCRIPTION
**Pull request by Breadbox2k19**
In light of their new found range attack, blackhive armor is readjusted.

### CODE REVIEW

**Comment by Juanfrank** [comment]
I believe they're okay as-is, any gun can pierce them anyhow

**Comment by Juanfrank** [comment]
And blackchitin is better than chitin lore-wise so they can't be below their vanilla counterparts

**Comment by Breadbox2k19** [comment]
Their armour is still higher than their vanilla counterpart if you are wondering.

**Comment by Juanfrank** [comment]
No it isn't

Core Patches for insects (Blunt/Sharp)>

Megascarab 1.5/0.5
Spelopede 6/2
Megaspider 12/4
(Centipede used as a reference for ratio for the Mammoth Worm 45/20)

**Comment by Breadbox2k19** [comment]
Black scarab and black spelopede still has a higher sharp armour than their basic counterpart while blackspider has the same, vanilla insectoid having blunt armour 3 times of their sharp armour is just nonsensical, it would imply that their carapace is somehow alot more rigid than steel plates.
Feel free to improve their blunt armour but it is the vanilla insectoids that has nonsensically overtuned armour stats. It also makes any sort of blunt weapon(like maces and warhammer) against them unusable, which you would think would be useful against armoured creatures but isn’t.

**Comment by Juanfrank** [comment]
> Black scarab and black spelopede still has a higher sharp armour than their basic counterpart while blackspider has the same, vanilla insectoid having blunt armour 3 times of their sharp armour is just nonsensical, it would imply that their carapace is somehow alot more rigid than steel plates.
> Feel free to improve their blunt armour but it is the vanilla insectoids that has nonsensically overtuned armour stats. It also makes any sort of blunt weapon(like maces and warhammer) against them unusable, which you would think would be useful against armoured creatures but isn’t.

I'm quoting the post-patch insectoid armor by CE

**Pull request closed without merging**
