### PR TITLE
Update AlphaAnimals_CE_Patch_RangedMechanoid.xml

### LINKED ISSUE #11: Increase Fireworm accuracy
It's crappy, nuff said.

### PR DESCRIPTION
**Pull request by Breadbox2k19**
Made siege gun compatible.
Remove AA_flamethrower Texpath, fireworm should shoot flame from its mouth instead of a tiny inferno canon to the side of its body.
Increased AA_flamethrower range since it's a mechanoid flamer.

### CODE REVIEW

**Review by Juanfrank — COMMENTED** [review]
Sorry for not adding a checklist for PR's, but I assume you have checked in dev mode for the non-existance of yellow or red errors (including melee attacks) and correct ammo spawn

**Comment by Breadbox2k19** [comment]
I’ll check again just incase.

**Comment by Juanfrank** [comment]
Self note that this hasn't been replaced in the test.

**Comment by Breadbox2k19** [comment]
Also, I personally make siege breaker fire 120mm with consideration to the performance of inferno canon centipede, as it stands Infernopede fires alot faster(It has a similar warm-up and cooldown, but no reload time), has much larger blast radius, 6 compared to 3 of a 100mm HE, half of the time siege breaker will be firing heat, which reduces the blast radius to 1.5.

The latter produces fragmentation but from my testing, they aren't very dangerous whereas getting caught in the blast radius results in instant death.

Making it fire a  relatively weak 100mm shell would makes it a really shitty infernopede.

**Comment by Juanfrank** [comment]
Fair enough, I reverted it back to 120mm while also increasing the warmuptime to encourage melee as a valid counter strategy, even to just stall firing the cannon.

I might consider increasing the Siegebreaker's movespeed since it has continuous track wheels whereas centipedes have micro legs (although their bodydef doesn't include them afaik)

**Pull request merged**
